name: simple-workflow

on: 
  workflow_dispatch:
  
  schedule: 
    - cron: "36 * * * *" # Planifie le workflow pour s'exécuter à chaque début d'heure

jobs:
  main_job:
    runs-on: ubuntu-latest # Définit l'environnement d'exécution
    steps:
      - name: Récupération du code source
        run: echo "Récupération du code source"

      - name: Vérification terminée
        run: echo "Vérification terminée"
